/*table schema*/
CREATE TABLE "BBM"."SPECIMEN" 
   (	"OID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"BLOODGROUP" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"RHFACTOR" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"UNITSRECEIVED" NUMBER(*,0), 
	"COLLECTEDON" TIMESTAMP (6) WITH TIME ZONE, 
	"EXPIRYDATE" TIMESTAMP (6), 
	"PERFORMEDBY" NUMBER(*,0), 
	"COMMENTS" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"STATUS" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

COMMENT ON COLUMN "BBM"."SPECIMEN"."RHFACTOR" IS 'Contains positive or negative as values; indicates the RH factor of a blood group';

CREATE UNIQUE INDEX "BBM"."SPECIMEN_PK" ON "BBM"."SPECIMEN" ("OID") 
  ;

ALTER TABLE "BBM"."SPECIMEN" MODIFY ("OID" NOT NULL ENABLE);

ALTER TABLE "BBM"."SPECIMEN" ADD CONSTRAINT "SPECIMEN_PK" PRIMARY KEY ("OID")
  USING INDEX  ENABLE;

--Procedure
CREATE TABLE "BBM"."PROCEDURE" 
   (	"OID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"PERFORMEDON" TIMESTAMP (6), 
	"PERFORMEDBY" NUMBER(*,0), 
	"SPECIMENOID" NUMBER(*,0), 
	"UNITSTRANSFUSED" NUMBER(*,0), 
	"COMMENTS" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"STATUS" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

CREATE UNIQUE INDEX "BBM"."PROCEDURE_PK" ON "BBM"."PROCEDURE" ("OID") 
  ;

ALTER TABLE "BBM"."PROCEDURE" MODIFY ("OID" NOT NULL ENABLE);

ALTER TABLE "BBM"."PROCEDURE" ADD CONSTRAINT "PROCEDURE_PK" PRIMARY KEY ("OID")
  USING INDEX  ENABLE;

ALTER TABLE "BBM"."PROCEDURE" ADD CONSTRAINT "FK_SPECIMENOID" FOREIGN KEY ("SPECIMENOID")
	  REFERENCES "BBM"."PROCEDURE" ("OID") ON DELETE CASCADE ENABLE NOVALIDATE;


--USER TABLE
CREATE TABLE "user" 
    ( 
     OID      NUMBER (*,0) GENERATED ALWAYS AS IDENTITY 
        ( START WITH 1 CACHE 20 ) , 
     FORENAME VARCHAR2 (20) , 
     SURNAME  VARCHAR2 (20) , 
     USERNAME VARCHAR2 (20) , 
     PASSWORD VARCHAR2 (20) , 
     STATUS   VARCHAR2 (1) 
    ) 
        TABLESPACE DATA 
        LOGGING 
    NO INMEMORY 
;

CREATE UNIQUE INDEX USER_PK ON "user" 
    ( 
     OID ASC 
    ) 
    TABLESPACE DATA 
    LOGGING 
;

ALTER TABLE "user" 
    ADD CONSTRAINT USER_PK PRIMARY KEY ( OID ) 
    USING INDEX USER_PK ;


